Add Gradle, and make tests work under gradle. Force bad class loading to fail before any tests are run, so we get NoClassDefFoundError just like in MC.